name: CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Copy .env
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     password: ${{ secrets.SSH_PASSWORD }}
    #     port: ${{ secrets.SSH_PORT }}
    #     source: ".env"
    #     target: "."
    #     overwrite: true
    - name: Publish bot to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jspmarc/kmkbot/prod
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: docker.pkg.github.com
        buildargs: KMK_BOT_CLIENT_ID=${{ secrets.BOT_CLIENT_ID }},KMK_BOT_SECRET=${{ secrets.BOT_SECRET }},KMK_BOT_TOKEN=${{ secrets.BOT_TOKEN }},KMK_GUILD_ID=${{ secrets.GUILD_ID }}
        tags: "latest"
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run bot over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: docker-compose pull && docker-compose build && docker-compose up -d --remove-orphans