name: CI/CD
on:
  push:
    branches: [ master ]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Run ESLint
      run: npx eslint app/ || npx eslint app/ --fix
  build:
    runs-on: ubuntu-latest
    needs: linting
    steps:
    - uses: actions/checkout@v2
    - name: Publish bot to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jspmarc/kmkbot/prod
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: docker.pkg.github.com
        buildargs: KMK_BOT_CLIENT_ID=${{ secrets.BOT_CLIENT_ID }},KMK_BOT_SECRET=${{ secrets.BOT_SECRET }},KMK_BOT_TOKEN=${{ secrets.BOT_TOKEN }},KMK_GUILD_ID=${{ secrets.GUILD_ID }}
        tags: "latest"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Update docker images/containers on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker-compose -f /kmkbot/docker-compose.yml pull
            docker-compose -f /kmkbot/docker-compose.yml up --build -d --remove-orphans